mykey = "petclinic"
ami = "ami-0889a44b331db0194"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "petclinic-jenkins-server-secgr-DE-06"
jenkins-server-tag = "Jenkins Server of Petclinic-DE-06"
jenkins-profile = "petclinic-jenkins-server-profile-DE-06"
jenkins-role = "petclinic-jenkins-server-role-DE-06"
